# Generated by Django 5.0.6 on 2024-07-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_investor_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investments',
            name='investment_date',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='investments',
            name='amount_invested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='current_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='return_on_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
