# Generated by Django 5.0.6 on 2024-07-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_remove_investments_investment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
