# Generated by Django 5.0.6 on 2024-07-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_rename_amount_invested_investments_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investments',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
