# Generated by Django 5.0.6 on 2024-07-10 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_companyincome_companyinvestors_delete_companyfinance'),
        ('investors', '0006_rename_comapny_name_investments_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
