# Generated by Django 5.0.6 on 2024-06-28 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_website', models.URLField(blank=True, null=True)),
                ('founding_date', models.DateField()),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('current_valuation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('previous_valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('funding_stage', models.CharField(choices=[('pre-seed', 'Pre-Seed'), ('seed', 'Seed'), ('series a', 'Series A'), ('series b', 'Series B'), ('series c', 'Series C')], default='pre-seed', max_length=20)),
                ('runway_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('pitch_deck', 'Pitch Deck'), ('financial_report', 'Financial Report'), ('other', 'Other')], default='bank_statement', max_length=20)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='company_documents/')),
                ('is_shared_with_investors', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFinance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_shared_with_investors', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
