# Generated by Django 5.0.6 on 2024-07-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='current_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
