# Generated by Django 5.0.6 on 2024-07-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_current_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='runway_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
