# Generated by Django 5.0.6 on 2024-07-02 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_runway_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('pitch_deck', 'Pitch Deck'), ('financial_report', 'Financial Report'), ('other', 'Other')], default='bank_statement', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='company_documents/')),
                ('is_shared_with_investors', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyDocuments',
        ),
    ]
