# Generated by Django 5.0.6 on 2024-07-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companyexpense_delete_companydocuments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyexpense',
            old_name='document_file',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='companyexpense',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='companyexpense',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='companyexpense',
            name='is_shared_with_investors',
        ),
        migrations.AddField(
            model_name='companyexpense',
            name='expense_bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
