# Generated by Django 5.0.6 on 2024-07-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companyexpense_delete_companydocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mobile_number',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
