# Generated by Django 5.0.6 on 2024-07-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_mobile_number'),
        ('companies', '0006_rename_document_file_companyexpense_document_and_more'),
    ]

    operations = [
    ]
