# Generated by Django 5.0.6 on 2024-07-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
