# Generated by Django 5.0.6 on 2024-07-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_company_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
