# Generated by Django 5.0.6 on 2024-07-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyexpense',
            old_name='document',
            new_name='document_file',
        ),
        migrations.AddField(
            model_name='companyexpense',
            name='document_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
