# Generated by Django 5.0.6 on 2024-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_rename_document_companyexpense_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexpense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
