# Generated by Django 5.0.6 on 2024-07-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_companyexpense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIncome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income_type', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInvestors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyFinance',
        ),
    ]
