from django.db import models
from django.contrib.auth.models import User

class Company(models.Model):
    """
    Represents a company in the system.

    Attributes:
        company_id (AutoField): The primary key for the company.
        company_name (CharField): The name of the company.
        company_logo (ImageField): The logo of the company.
        company_website (URLField): The website URL of the company.
        founding_date (DateField): The date when the company was founded.
        industry (CharField): The industry of the company.
        current_valuation (DecimalField): The current valuation of the company.
        previous_valuation (DecimalField): The previous valuation of the company.
        funding_stage (CharField): The funding stage of the company.
        runway_status (CharField): The status of the company's runway.
        created_at (DateTimeField): The date and time when the company was created.
        updated_at (DateTimeField): The date and time when the company was last updated.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_id = models.AutoField(primary_key=True, unique=True)
    company_name = models.CharField(max_length=100, null=True, blank=True)
    company_logo = models.ImageField(upload_to='company_logos/', blank=True, null=True)
    company_website = models.URLField(max_length=200, blank=True, null=True)
    founding_date = models.DateField(blank=True, null=True)
    company_address = models.CharField(max_length=100, null=True, blank=True)
    number_of_employees = models.IntegerField(null=True, blank=True)
    industry = models.CharField(max_length=100, null=True, blank=True)
    current_valuation = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    previous_valuation = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    funding_stage = models.CharField(
        max_length=20,
        choices=[('pre-seed', 'Pre-Seed'), ('seed', 'Seed'), ('series a', 'Series A'), ('series b', 'Series B'), ('series c', 'Series C')],
        default='pre-seed'
    )
    runway_status = models.CharField(max_length=100,blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

class CompanyFinance(models.Model):
    """
    Represents the financial information of a company.

    Attributes:
        id (int): The unique identifier for the company finance record.
        company_id (Company): The foreign key to the associated company.
        period (date): The period for which the financial information is recorded.
        revenue (Decimal): The revenue generated by the company during the period.
        is_shared_with_investors (bool): Indicates whether the financial information is shared with investors.
        created_at (datetime): The date and time when the record was created.
        updated_at (datetime): The date and time when the record was last updated.
    """
    id = models.AutoField(primary_key=True)
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    period = models.DateField()
    revenue = models.DecimalField(max_digits=20, decimal_places=2)
    profit_loss = models.DecimalField(max_digits=20, decimal_places=2)
    expenses = models.DecimalField(max_digits=20, decimal_places=2)
    is_shared_with_investors = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class CompanyDocuments(models.Model):
    """
    Represents the documents associated with a company.

    Attributes:
        id (AutoField): The primary key for the document.
        company_id (ForeignKey): The foreign key to the associated Company model.
        document_name (CharField): The name of the document.
        document_type (CharField): The type of the document.
        document_file (FileField): The file field to store the document file.
        is_shared_with_investors (BooleanField): Indicates if the document is shared with investors.
        created_at (DateTimeField): The date and time when the document was created.
        updated_at (DateTimeField): The date and time when the document was last updated.
    """

    id = models.AutoField(primary_key=True)
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)
    document_name = models.CharField(max_length=100)
    document_type = models.CharField(max_length=20,
        choices=[('bank_statement', 'Bank Statement'), ('pitch_deck', 'Pitch Deck'), ('financial_report', 'Financial Report'),('other', 'Other')],
        default='bank_statement'
    )
    document_file = models.FileField(upload_to='company_documents/', null=True, blank=True)
    is_shared_with_investors = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)